require('./unit/functions/calcStatsCombat.dev.js')
require('./unit/functions/getAbilityTypeByCaption.dev.js')
require('./unit/functions/nextProfessions.dev.js')
require('./unit/functions/prevProfessions.dev.js')

require('./unit/abstract-fabric/items/Item.dev.js')

require('./unit/classes/character/Abilities.dev.js')
require('./unit/classes/character/Cargo.dev.js')
require('./unit/classes/character/Cast.dev.js')
require('./unit/classes/character/Character.dev.js')
require('./unit/classes/character/Coords.dev.js')
require('./unit/classes/character/Health.dev.js')
require('./unit/classes/character/Inventory.dev.js')
require('./unit/classes/character/Leveler.dev.js')
require('./unit/classes/character/Mana.dev.js')
require('./unit/classes/character/StatsCombat.dev.js')
require('./unit/classes/character/Target.dev.js')
require('./unit/classes/character/Wear.dev.js')
require('./unit/classes/Bootcamp.dev.js')
require('./unit/classes/Delayer.dev.js')
require('./unit/classes/Shop.dev.js')
require('./unit/classes/University.dev.js')

require('./unit/abstract-fabric/abilities/abilityFabric.dev.js')
require('./unit/abstract-fabric/activities/actitvityFabric.dev.js')
require('./unit/abstract-fabric/items/Consumable.dev.js')
require('./unit/abstract-fabric/items/Fake.dev.js')

require('./integration/cycle-aura.dev.js')
require('./integration/cycle-buff.dev.js')
require('./integration/cycle-debuff.dev.js')
require('./integration/cycle-fight.dev.js')
require('./integration/cycle-persist.dev.js')
require('./integration/cycle-skill.dev.js')
require('./integration/fight.dev.js')
require('./integration/show-abilities-to-train.dev.js')
