require('./classes/character/Character.spec.js')
require('./classes/character/Health.spec.js')
require('./classes/character/Inventory.spec.js')
require('./classes/character/Cargo.spec.js')
require('./classes/character/Leveler.spec.js')
require('./classes/character/Wear.spec.js')
require('./functions/takePercent.spec.js')
